expect-actual info about use ios pod in iosMain
Alex009/kmm.icerock.dev pull request #25
Opened 2022-04-08 11:14 UTC by anton6tak

2022-04-12 13:27 UTC, Alex009 requested changes

2022-04-12 13:27 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/expect-actual.md
> +      - Как использовать функцию из файла в iOS проекте: при интерпретации общего кода в библиотеку для iOS, интерпретатор упаковывает всё, что находится вне классов в свой класс с постфиксом Kt, поэ
при компиляции.
компилятор складывает все top level декларации (функции и свойства вне класса) в синтетический класс <fileName>Kt

2022-04-13 04:55 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/expect-actual.md
> +      - Как использовать функцию из файла в iOS проекте: при интерпретации общего кода в библиотеку для iOS, интерпретатор упаковывает всё, что находится вне классов в свой класс с постфиксом Kt, поэ
поправил

2022-04-14 03:42 UTC, Alex009 approved these changes

2022-04-14 03:42 UTC, merged