about 1 way to use settings
Alex009/kmm.icerock.dev pull request #28
Opened 2022-04-11 11:55 UTC by anton6tak

2022-04-12 13:26 UTC, Alex009 requested changes

2022-04-12 13:26 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +    val delegate: SharedPreferences // ...
вот про этот момент надо детальнее - ребята на этом ломаются

2022-04-12 13:26 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +## Подключение напрямую к платформе
перед этим надо еще вариант - использование no-arg модуля.
https://github.com/russhwolf/multiplatform-settings#no-arg-module

2022-04-12 13:26 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +Однако, этого не достаточно, чтобы библиотека стала доступна и на iOS. Чтобы это сделать, необходимо добавить бинарники классов библиотеки к iOS фреймворку, в который собирается общий код.
необходимо добавить классы библиотеки в header iOS фреймворка, чтобы они стали видны из swift.

2022-04-12 13:26 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +Но, при желании, подключить бинарники библиотеки можно, для этого добавьте следующие строчки в раздел `cocoapods/framework` в `shared/build.gradle` файле:
добавить классы в хидер можно

2022-04-12 13:26 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +transitiveExport = true
не надо транзитивить - так лишнего наэкспортируешь

2022-04-12 13:26 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +1. Подключите multiplatform-settings напрямую к платформам, убедитесь, что все работает
тут вариант про no-arg надо еще :)

2022-04-13 04:49 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +    val delegate: SharedPreferences // ...
Расписал детальнее, с примером

2022-04-13 04:49 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +## Подключение напрямую к платформе
добавил

2022-04-13 04:49 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +Однако, этого не достаточно, чтобы библиотека стала доступна и на iOS. Чтобы это сделать, необходимо добавить бинарники классов библиотеки к iOS фреймворку, в который собирается общий код.
поправил

2022-04-13 04:49 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +Но, при желании, подключить бинарники библиотеки можно, для этого добавьте следующие строчки в раздел `cocoapods/framework` в `shared/build.gradle` файле:
поправил

2022-04-13 04:49 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +transitiveExport = true
поправил

2022-04-13 04:49 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +1. Подключите multiplatform-settings напрямую к платформам, убедитесь, что все работает
добавил

2022-04-14 04:02 UTC, Alex009 approved these changes

2022-04-14 04:03 UTC, merged