Moko 1057 kmm page
Alex009/kmm.icerock.dev pull request #3
Opened 2022-01-25 09:15 UTC by anton6tak

2022-01-26 17:00 UTC, Alex009 requested changes

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/_category_.json
> +  "label": "Основы разработки Kotlin Multiplatform Mobile"
надо назвать "3. Основы разработки Kotlin Multiplatform Mobile"

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/expect-actual.md
> +Изучить побробнее можно на [официальном сайте](https://kotlinlang.org/docs/mpp-connect-to-apis.html)
нужна еще практика, кодлабу найти какую нибудь или статью где простенький пример делается типа логгера или своего Settings с sharedpref/userdefaults

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm-intro.md
> +- Сериализация данных при помощи KotlinX Serialization
настройка kmm в gradle
использование multiplatform-settings
что такое multiplatform библиотеки и отличия от других библиотек
где искать и как выбирать kmm библиотеки

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm-intro.md
> +Если вы уже знакомы со всем этим, можете переходить к следующему разделу
к практике :)

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +Для начала, чтобы получше разобраться, чем же так хорош Kotlin Multiplatform Mobile, советуем прочитать нашу небольшую [статью](https://vc.ru/services/167078-kak-kotlin-multiplatform-pomogaet-sokrati
тебя заинтересовала эта статья? думаешь имеет смысл ее первой давать?

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +1. Разберитесь со структурой KMM приложения
как разберитесь? самостоятельно?)

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kotlinx-serialization.md
> +# Kotlinx serialization
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serialization-guide.md название подправь ровно под то как в доке называют.
`Kotlin Serialization`

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kotlinx-serialization.md
> +Основное ее преимущество - совместимость с Kotlin Multiplatform. Преобразование в общем коде в JSON и обратно, используя Kotlinx serialization, будет работать как на Android, так и на iOS
и на всех остальных платформах поддерживаемых Kotlin

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/ktor-client.md
> +1. [Инструкция](https://ktor.io/docs/intellij-idea.html) по созданию Ktor приложения возможностями IntelliJ IDEA
зачем просить мобильщика создавать проект бекендовый? не релевантная ссылка

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/ktor-client.md
> +# Ktor-client
название ровно по доке надо взять.  https://ktor.io/docs/getting-started-ktor-client.html
`Ktor Client﻿`

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/ktor-client.md
> +1. [Инструкция](https://ktor.io/docs/gradle.html) по добавлению Ktor в существующий gradle-проект, создание сервера
зачем мобильщику идти сервер создавать?)
у нас в этом разделе цель мобильщика научить кидать запросы с ktor. кидать json'чики и получать json'чики. и не только их. нафик не надо никакие серверные фигни :)

2022-01-26 17:00 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/practice.md
> +# Практическое задание
практика все теже андроид и айос приложения гитхаба, но только теперь надо их в один реп соединить, добавить общую логику где будет вся сеть и хранение токена

2022-01-27 03:49 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm-intro.md
> +- Сериализация данных при помощи KotlinX Serialization
https://www.youtube.com/watch?v=oBv1QykLAXc

2022-01-27 03:51 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm-intro.md
> +- Сериализация данных при помощи KotlinX Serialization
https://github.com/terrakok/kmm-awesome
https://libs.kmp.icerock.dev
https://kamp.petuska.dev

2022-01-27 03:55 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +Для начала, чтобы получше разобраться, чем же так хорош Kotlin Multiplatform Mobile, советуем прочитать нашу небольшую [статью](https://vc.ru/services/167078-kak-kotlin-multiplatform-pomogaet-sokrati
https://kotlinlang.org/lp/mobile/

2022-01-27 03:56 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +1. Разберитесь со структурой KMM приложения
https://kotlinlang.org/docs/mpp-discover-project.html

2022-01-27 11:44 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/_category_.json
> +  "label": "Основы разработки Kotlin Multiplatform Mobile"
Исправил

2022-01-27 11:44 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/expect-actual.md
> +Изучить побробнее можно на [официальном сайте](https://kotlinlang.org/docs/mpp-connect-to-apis.html)
Нашел кодлабу, она мб немного большая, но зато там есть и настройка кмм, и expect/actual

2022-01-27 11:52 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm-intro.md
> +Если вы уже знакомы со всем этим, можете переходить к следующему разделу
Исправил

2022-01-27 11:52 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +Для начала, чтобы получше разобраться, чем же так хорош Kotlin Multiplatform Mobile, советуем прочитать нашу небольшую [статью](https://vc.ru/services/167078-kak-kotlin-multiplatform-pomogaet-sokrati
Добавил офф ресурс, изменил порядок и описание

2022-01-27 11:52 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kotlinx-serialization.md
> +Основное ее преимущество - совместимость с Kotlin Multiplatform. Преобразование в общем коде в JSON и обратно, используя Kotlinx serialization, будет работать как на Android, так и на iOS
исправил

2022-01-27 11:53 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/ktor-client.md
> +1. [Инструкция](https://ktor.io/docs/intellij-idea.html) по созданию Ktor приложения возможностями IntelliJ IDEA
Убрал

2022-01-27 11:54 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/ktor-client.md
> +# Ktor-client
Исправил

2022-01-27 11:56 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/ktor-client.md
> +1. [Инструкция](https://ktor.io/docs/gradle.html) по добавлению Ktor в существующий gradle-проект, создание сервера
Убрал, добавил ссылку на раздел документации про создание запросов

2022-01-28 09:12 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm-intro.md
> +- Сериализация данных при помощи KotlinX Serialization
Добавил, вынес в памятку

2022-02-02 13:46 UTC, Alex009 commented on university/1-android-basics/practice.md
> +     clearPrefs()
как я уже обозначил - схема некорректная, ошибки в API. надо исправлять

2022-02-02 16:13 UTC, Alex009 requested changes

2022-02-02 16:13 UTC, Alex009 commented on university/2-ios-basics/practice.md
> +     repoList: StateFlow:List:RepoEntity?
нет в ios никакого stateflow и suspend.

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/expect-actual.md
> +- Добавьте actual-реализацию функции greeting для iOS
не хватает понимания что в этой актуал функции делаться должно. и почему саспенд функция?

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/expect-actual.md
> +Представим ситуацию, вы хотите использовать [Material Buttons](https://material.io/components/buttons) для верстки кнопок Android и iOS приложений. В Android эта библиотека доступна по умолчанию, а д
а при чем тут кнопки материал? не понял я тут чото

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +Таргеты мультиплатформенной библиотеки - целевая платформа, на которой будет выполняться скомпилированная библиотека. Со списком всех таргетов, поддерживаемых KMM можете ознакомиться по [ссылке](http
поддерживаемых Kotlin Multiplatform.

Kotlin Multiplatform Mobile - это подмножество всей Kotlin Multiplatform, с специфичным тулингом чисто под мобилки.
я пояснял это подробно вот тут - https://youtu.be/jJWDlsETb3A?t=125

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +- jvm - для работы приложений на Java Virtual Machine
в скобочках укажи что jvm либы поддерживаются на android тоже автоматически

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +- simulator_x64 - для симуляторов iOS на M1
список платформ выше у тебя указан, чтож ты оттуда не скопировал чтоб не ошибиться?
ios_simulator_arm64

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +}
сорссеты вообще не роляют. главное это блок kotlin где таргеты включаются

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +- библиотека поддерживает симуляторы и устройства iOS, но не на M1
надо скриншот с надписями на нем поясняющий как понять из мавена что мы тут поддерживаем :)

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +При выборе библиотеки обязательно обращайте внимание на наличие таргетов `jvm`, `androidJvm` `ios_arm64` `ios_x64`, `simulator_x64`. Не забывайте проверить дату последнего релиза, чтобы удостоверитьс
айос симулятор исправить надо

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +- [libs.kmp.icerock.dev](https://libs.kmp.icerock.dev) - библиотеки, представленные на сайте, поддерживают минимум три таргета, необходимые нам для разработки
убери приписку. я же уже повторял что минимум мобильные таргеты это на kmm awesome, а не у нас. у нас есть и просто мультиплатформенные либы где нет айос например

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kotlinx-serialization.md
> +Kotlin Serialization - это библиотека, предназначенная для удобной cериализации классов
"например, для преобразования строки в json объект и обратно"

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kotlinx-serialization.md
> +Kotlin Serialization - это библиотека, предназначенная для удобной cериализации классов
и помимо json поддерживаются другие форматы, например protobuf

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/kotlinx-serialization.md
> +- Как получить сериализатор списка или Dictionary?
в котлине нет словаря. есть Map

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +В работе мы делегировали работу с хранилищем устройства классу KeyValueStorage.
"мы делегируем"

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/practice.md
> +<iframe width="360" height="800" src="//www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FMh3ga5XAzyJNCY87NBp01G%2FGit_test%3Fnode-id%3D4%253A600%26scaling%3Dmin-zoom%26p
думаю дизайн тут можно убрать. описание подправить - "Нужно объединить ранее сделанные Android и iOS приложения в единый репозиторий, добавить модуль общего кода и перенести из Android и iOS логику работы с сетью и хранением токена в общий код"

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/practice.md
> +Функциональные возможности:
можно указать "Функциональные возможности остаются ровно теже самые" и потом перечислить их, да, как щас

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/practice.md
> +1. Сохранять токен авторизации в хранилище устройства: SharedPreferences для Android и NSUserDefaults для iOS. Работу с хранилищем делегировать классу KeyValueStorage
сохранять используя multiplatform-settings. не надо тут уже про шаред и юзер дефолтсы

2022-02-02 16:13 UTC, Alex009 commented on university/3-kotlin-multiplatform-mobile/practice.md
> +  clearPrefs()
весь апи вьюмоделей переделываем :)

2022-02-03 04:28 UTC, anton6tak commented on university/1-android-basics/practice.md
> +     clearPrefs()
исправил

2022-02-04 03:22 UTC, anton6tak commented on university/2-ios-basics/practice.md
> +     repoList: StateFlow:List:RepoEntity?
исправил

2022-02-04 03:23 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/expect-actual.md
> +- Добавьте actual-реализацию функции greeting для iOS
добавил описание, саспенд - опечатка

2022-02-04 03:23 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/expect-actual.md
> +Представим ситуацию, вы хотите использовать [Material Buttons](https://material.io/components/buttons) для верстки кнопок Android и iOS приложений. В Android эта библиотека доступна по умолчанию, а д
тут у меня была идея про материал библиотеку сначала сделать, потом передумал а начало забыл стререть

2022-02-04 03:24 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +Таргеты мультиплатформенной библиотеки - целевая платформа, на которой будет выполняться скомпилированная библиотека. Со списком всех таргетов, поддерживаемых KMM можете ознакомиться по [ссылке](http
поправил

2022-02-04 03:24 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +- jvm - для работы приложений на Java Virtual Machine
добавил

2022-02-04 03:24 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/multiplatform-settings.md
> +В работе мы делегировали работу с хранилищем устройства классу KeyValueStorage.
поправил

2022-02-04 03:24 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/practice.md
> +<iframe width="360" height="800" src="//www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FMh3ga5XAzyJNCY87NBp01G%2FGit_test%3Fnode-id%3D4%253A600%26scaling%3Dmin-zoom%26p
исаправил

2022-02-04 03:25 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/practice.md
> +Функциональные возможности:
поправил

2022-02-04 03:25 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/practice.md
> +1. Сохранять токен авторизации в хранилище устройства: SharedPreferences для Android и NSUserDefaults для iOS. Работу с хранилищем делегировать классу KeyValueStorage
поправил

2022-02-04 03:25 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/practice.md
> +  clearPrefs()
переделал

2022-02-11 04:04 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +- simulator_x64 - для симуляторов iOS на M1
поправил

2022-02-11 04:04 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +}
поправил

2022-02-11 04:04 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +- библиотека поддерживает симуляторы и устройства iOS, но не на M1
добавил

2022-02-11 04:04 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +При выборе библиотеки обязательно обращайте внимание на наличие таргетов `jvm`, `androidJvm` `ios_arm64` `ios_x64`, `simulator_x64`. Не забывайте проверить дату последнего релиза, чтобы удостоверитьс
поправил

2022-02-11 04:05 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kmm.md
> +- [libs.kmp.icerock.dev](https://libs.kmp.icerock.dev) - библиотеки, представленные на сайте, поддерживают минимум три таргета, необходимые нам для разработки
поправил

2022-02-11 04:05 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kotlinx-serialization.md
> +Kotlin Serialization - это библиотека, предназначенная для удобной cериализации классов
поправил

2022-02-11 04:05 UTC, anton6tak commented on university/3-kotlin-multiplatform-mobile/kotlinx-serialization.md
> +- Как получить сериализатор списка или Dictionary?
исправил

2022-03-03 06:14 UTC, Alex009 approved these changes

2022-03-03 06:17 UTC, merged