7 data sharing
Alex009/kmm.icerock.dev pull request #45
Opened 2022-05-19 11:33 UTC by anton6tak

2022-05-23 11:42 UTC, Alex009 commented on learning/libraries/moko/moko-network.md
> +***ВИДОСИК***
https://www.youtube.com/watch?v=98r5muoeO7U

2022-05-23 11:42 UTC, Alex009 requested changes

2022-05-23 11:42 UTC, Alex009 commented on learning/libraries/moko/moko-network.md
> +## Features
перед фичами описать про модуль network-errors и метод его `registerAllNetworkMappers`

2022-05-24 03:53 UTC, anton6tak commented on learning/libraries/moko/moko-network.md
> +***ВИДОСИК***
добавил

2022-05-24 03:53 UTC, anton6tak commented on learning/libraries/moko/moko-network.md
> +## Features
добавил

2022-05-24 04:32 UTC, Alex009 requested changes

2022-05-24 04:32 UTC, Alex009 commented on university/6-unit-lists/moko-paging.md
> +посмотрите ***видео*** и изучите [страницу](/learning/libraries/moko/moko-paging) библиотеки в базе знаний.
смерижть надо актуальную ветку сюда, а то тут лишние изменения)

2022-05-24 04:32 UTC, Alex009 commented on university/7-data-sharing/practice.md
> +4. ***ДОБАВИТЬ Дизайн iOS***
мне дизайн надо добавить

2022-05-24 04:55 UTC, merged