9-runtime-permissions
Alex009/kmm.icerock.dev pull request #48
Opened 2022-05-30 04:18 UTC by anton6tak

2022-06-01 03:49 UTC, Alex009 requested changes

2022-06-01 03:49 UTC, Alex009 commented on learning/libraries/moko/moko-geo.md
> +***ВИДОСИК***
@Alex009 сделать видос

2022-06-01 03:49 UTC, Alex009 commented on learning/libraries/moko/moko-media.md
> +***ВИДОСИК***
@Alex009 сделать видос

2022-06-01 03:49 UTC, Alex009 commented on learning/libraries/moko/moko-media.md
> +- выбор файлов на устройстве (Android only)
для ios тоже

2022-06-01 03:49 UTC, Alex009 commented on learning/libraries/moko/moko-permissions.md
> +***ВИДОСИК***
@Alex009 сделать видос

2022-06-01 03:49 UTC, Alex009 commented on university/9-runtime-permissions/moko-geo.md
> +Чтобы лучше понимать работу библиотеки, разберите то, как реализована работа с локаицей на платформах:
локацией

2022-06-01 03:49 UTC, Alex009 commented on university/9-runtime-permissions/moko-media.md
> +## Android
заменить на гайды по выбору из галереи, получению фото с камеры

2022-06-01 03:49 UTC, Alex009 commented on university/9-runtime-permissions/moko-media.md
> +## iOS
заменить на гайды по выбору из галереи, получению фото с камеры

2022-06-01 03:49 UTC, Alex009 commented on university/9-runtime-permissions/moko-permissions.md
> +Для начала, ознакомьтесь с [Readme](https://github.com/icerockdev/moko-permissions#mobile-kotlin-runtime-permissions-multiplatform-controller) библиотеки.
https://github.com/icerockdev/moko-permissions#readme

2022-06-01 03:49 UTC, Alex009 commented on university/9-runtime-permissions/moko-permissions.md
> +[Список разрешений](https://github.com/icerockdev/moko-permissions#mobile-kotlin-runtime-permissions-multiplatform-controller), которые позволяет получить библиотека.
https://github.com/icerockdev/moko-permissions#list-of-supported-permissions

2022-06-01 03:49 UTC, Alex009 commented on university/9-runtime-permissions/practice.md
> +## Технические требования
вьюмодель создания ишшусы должна использовать MediaPickerController

2022-06-01 03:49 UTC, Alex009 commented on university/9-runtime-permissions/work-with-permissions.md
> +   - Из состояния DeniedAlways перейти в Granted можно только изменив разрешение в настройках приложения, поэтому необходимо реализовать это поведение
необходимо реализовать переход пользователя в настройки приложения для изменения разрешений

2022-06-01 05:23 UTC, anton6tak commented on learning/libraries/moko/moko-media.md
> +- выбор файлов на устройстве (Android only)
поправил

2022-06-01 05:23 UTC, anton6tak commented on university/9-runtime-permissions/moko-geo.md
> +Чтобы лучше понимать работу библиотеки, разберите то, как реализована работа с локаицей на платформах:
поправил

2022-06-01 05:23 UTC, anton6tak commented on university/9-runtime-permissions/moko-media.md
> +## Android
заменил на гайды

2022-06-01 05:23 UTC, anton6tak commented on university/9-runtime-permissions/moko-media.md
> +## iOS
заменил на  гайды

2022-06-01 05:23 UTC, anton6tak commented on university/9-runtime-permissions/moko-permissions.md
> +Для начала, ознакомьтесь с [Readme](https://github.com/icerockdev/moko-permissions#mobile-kotlin-runtime-permissions-multiplatform-controller) библиотеки.
поправил

2022-06-01 05:23 UTC, anton6tak commented on university/9-runtime-permissions/moko-permissions.md
> +[Список разрешений](https://github.com/icerockdev/moko-permissions#mobile-kotlin-runtime-permissions-multiplatform-controller), которые позволяет получить библиотека.
поправил

2022-06-01 05:23 UTC, anton6tak commented on university/9-runtime-permissions/practice.md
> +## Технические требования
добавил требование

2022-06-01 05:23 UTC, anton6tak commented on university/9-runtime-permissions/work-with-permissions.md
> +   - Из состояния DeniedAlways перейти в Granted можно только изменив разрешение в настройках приложения, поэтому необходимо реализовать это поведение
поправил

2022-06-02 03:40 UTC, Alex009 requested changes

2022-06-02 03:40 UTC, Alex009 commented on university/9-runtime-permissions/moko-media.md
> +  - [Получение фото от камеры](http://developer.alexanderklimov.ru/android/photocamera.php)
https://developer.android.com/guide/components/intents-common#ImageCapture

2022-06-02 03:40 UTC, Alex009 commented on university/9-runtime-permissions/moko-media.md
> +  - [Выбор фото из галереи устройства](https://handyopinion.com/pick-image-from-gallery-in-kotlin-android/)
https://developer.android.com/guide/components/intents-common#GetFile

2022-06-02 03:40 UTC, Alex009 commented on university/9-runtime-permissions/moko-media.md
> +  - [Выбор фото из галереи](https://russianblogs.com/article/52391027975/)
https://developer.apple.com/documentation/photokit/selecting_photos_and_videos_in_ios

2022-06-02 03:40 UTC, Alex009 commented on university/9-runtime-permissions/moko-media.md
> +  - [Получение фото от камеры](https://russianblogs.com/article/49971508514/)
https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/CameraAndPhotoLib_TopicsForIOS/Articles/TakingPicturesAndMovies.html#//apple_ref/doc/uid/TP40010406

2022-06-02 03:57 UTC, anton6tak commented on university/9-runtime-permissions/moko-media.md
> +  - [Получение фото от камеры](https://russianblogs.com/article/49971508514/)
добавил

2022-06-02 03:57 UTC, anton6tak commented on university/9-runtime-permissions/moko-media.md
> +  - [Выбор фото из галереи](https://russianblogs.com/article/52391027975/)
добавил

2022-06-02 03:57 UTC, anton6tak commented on university/9-runtime-permissions/moko-media.md
> +  - [Выбор фото из галереи устройства](https://handyopinion.com/pick-image-from-gallery-in-kotlin-android/)
добавил

2022-06-02 03:57 UTC, anton6tak commented on university/9-runtime-permissions/moko-media.md
> +  - [Получение фото от камеры](http://developer.alexanderklimov.ru/android/photocamera.php)
добавил

2022-06-18 16:21 UTC, Alex009 commented on learning/libraries/moko/moko-media.md
> +***ВИДОСИК***
отложено

2022-06-18 16:21 UTC, Alex009 commented on learning/libraries/moko/moko-geo.md
> +***ВИДОСИК***
отложено

2022-06-18 16:21 UTC, Alex009 approved these changes

2022-06-18 16:24 UTC, merged