best practices
Alex009/kmm.icerock.dev pull request #49
Opened 2022-06-07 14:40 UTC by anton6tak

2022-06-08 04:11 UTC, Alex009 requested changes

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- стейты не должны содержать onClick-лямбду
не стоит, с композом не работает.
https://gitlab.icerockdev.com/campus/campus-android-remaster/-/blob/develop/app/src/main/java/ru/campus/mobile/app/ui/RemoteStateContent.kt

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- [функции](function)
Продумывайте имена функций и их содержимое

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- не работайте с доменными классами от сервера, просто преобразуйте их в свои и используйте везде свои (про маппинг тут подробнее сказать)
сетевые сущности и доменные

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- Новые зависимости добавляйте сразу в libs, в нужный блок, а не хардкодом
в скобках указать (Version Catalog) с ссылкой на базу знаний

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- Новые зависимости добавляйте сразу в libs, в нужный блок, а не хардкодом
это ток начиная с 4 блока

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- Не используйте MR ресурсы на платформе, на андроид есть R, на iOS есть R.swift
тут доуточнить - в мультиплатформе должны быть только те ресурсы, которые управляются общей логикой. если же общая логика никк не трогает какой-то ресурс - то он должен быть на платформе, а не в общей

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- Не создавайте дополнительную переменную, если сразу же после ее создания присваиваете её куда-то, без каких либо модификаций
показать кейсы и перефразировать поинт

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- уделяйте пристальное внимание тому, как вы обрабатываете стейты
пример бы

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- добавление кастомных вьюх через код, а не через IB
не в ту сторону воюешь

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- проверяйте имя файла картинки, не должна быть белиберда из фигмы
отойти от тезиса "в фигме белиберда"

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- не используйте константы для размера отступа или вьюхи
раскрыть когда это нужно а когда нет

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- уделяйте пристальное внимание тому, как вы обрабатываете стейты
уточнить

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- Конструкция `with(binding...)` для XML элементов. Не стоит ей злоупотреблять. Используйте ее только если вам предстоит работа с элементами минимум 3 уровня вложенности и обращение к этим элементам
поприкидывать примеры

2022-06-08 04:11 UTC, Alex009 commented on university/memos/best-practices.md
> +- ***Про верстку сверху вниз и снизу вверх, отступы от элементов, которые рядом, а не просто от главного экрана приложения***
про переключение превью указать

2022-06-09 06:06 UTC, Alex009 requested changes

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- Не используйте MR ресурсы на платформе, на андроид есть R, на iOS есть R.swift. (ссылка на четвертый блок, где будет пояснение).
начиная с 4

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +  - перефразировать
не забудь)

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- Не используйте форскасты
"когда их использовать вы поймете, когда дорастете до мидлов" :)

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +  - версвтать свой тулбар
дублирует 2 пункт кажись

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- exitButton.setOnClickListener { viewModel.onExitButtonPressed() } - UI должен говорить вьюмодели - нажми на мою кнопку, а вьюмодель сама уже будет делать то, что надо
подпунктами сделать

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- exitButton.setOnClickListener { viewModel.onExitButtonPressed() } - UI должен говорить вьюмодели - нажми на мою кнопку, а вьюмодель сама уже будет делать то, что надо
выделение кодом не забудь

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- exitButton.setOnClickListener { viewModel.onExitButtonPressed() } - UI должен говорить вьюмодели - нажми на мою кнопку, а вьюмодель сама уже будет делать то, что надо
не "нажми на мою кнопку, а вьюмодель сама уже будет делать то, что надо"
а "нажата кнопка выхода, а вьюмодель сама уже будет делать то, что надо"

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- exitButton.setOnClickListener { viewModel.onExitButtonPressed() } - UI должен говорить вьюмодели - нажми на мою кнопку, а вьюмодель сама уже будет делать то, что надо
публичные функции в вьюмодели именуем от вопроса "когда эту функцию вызывать?".
разработчик который интегрирует вьюмодель в платформу должен по апи понять когда вызывать метод

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- используйте `weakLambda(...)` - сохранят receiver слабой ссылкой
сссылку на полное поясенение

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- используйте аннотации `@Throws(...)` толко в случае, если это попадает в swift код
ссылку на офф доку с пояснением

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- свои кастомные эксепшены, которые мы сами кидаем, наследуем от RuntimeException()
либо от более конкретных его наследников

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- свои кастомные эксепшены, которые мы сами кидаем, наследуем от RuntimeException()
не забываем про cause

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- расставляйте элементы UI в xml в хронологическом порядке, а не абы как, чтобы те элементы, которые сверху экрана (тулбар например) объявлялись сверху в xml
это не хронологический :)
это порядок отрисовки

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- форматирование кода, отключить галку, чтобы не добавлялась лишняя запятая ![img.png](media/useless-comma.png)
это в кодстайл надо :)

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- помните про конфикты имен Kotlin и iOS, если у вас будет свойство description, [вот](../../learning/kotlin-multiplatform/mobile-highlights#конфликты-имен-на-ios) что будет на iOS
если у вас НАПРИМЕР свойство дескрипшен

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +  ```
пример не нравится, подумай еще кейсы

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- цвет для контроллера надо устанавливать в AppDelegate, только создали навконтроллер - сразу ставим цвет `navigationController?.navigationBar.barStyle = .black`
указать что если это глобально надо. и взять из слака ответ Дорофеева

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- используйте слабые ссылки на self
не забывайте про циклы сильных ссылок (тут ссылку на https://kmm.icerock.dev/learning/memory_management) и ставьте [weak self] там где он нужен

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +  - savedInstanceState - переменная для хранения данных из бандла, которая передается в onCreate(). Если данные из бандла пустые или savedInstanceState == null, тогда нужно создать новый навграф, а е
не про создание нового графа, а про смену стартового экрана в графе

2022-06-09 06:06 UTC, Alex009 commented on university/memos/best-practices.md
> +- подписываться на вьюмодель должна создаваться сразу, как только мы создали вью
объяснить

2022-06-10 01:12 UTC, anton6tak commented on university/memos/best-practices.md
> +- стейты не должны содержать onClick-лямбду
поправил

2022-06-10 01:12 UTC, anton6tak commented on university/memos/best-practices.md
> +- [функции](function)
поправил

2022-06-10 01:16 UTC, anton6tak commented on university/memos/best-practices.md
> +- не работайте с доменными классами от сервера, просто преобразуйте их в свои и используйте везде свои (про маппинг тут подробнее сказать)
поправил

2022-06-10 01:16 UTC, anton6tak commented on university/memos/best-practices.md
> +- Новые зависимости добавляйте сразу в libs, в нужный блок, а не хардкодом
поправил

2022-06-10 01:17 UTC, anton6tak commented on university/memos/best-practices.md
> +- Не используйте MR ресурсы на платформе, на андроид есть R, на iOS есть R.swift
поправл

2022-06-10 01:19 UTC, anton6tak commented on university/memos/best-practices.md
> +- добавление кастомных вьюх через код, а не через IB
поправил

2022-06-10 01:19 UTC, anton6tak commented on university/memos/best-practices.md
> +- проверяйте имя файла картинки, не должна быть белиберда из фигмы
поправил

2022-06-10 01:23 UTC, anton6tak commented on university/memos/best-practices.md
> +- не используйте константы для размера отступа или вьюхи
дописал

2022-06-10 01:23 UTC, anton6tak commented on university/memos/best-practices.md
> +- уделяйте пристальное внимание тому, как вы обрабатываете стейты
поправил

2022-06-10 01:27 UTC, anton6tak commented on university/memos/best-practices.md
> +- Не используйте форскасты
поправил

2022-06-10 01:27 UTC, anton6tak commented on university/memos/best-practices.md
> +  - версвтать свой тулбар
убрал

2022-06-10 01:30 UTC, anton6tak commented on university/memos/best-practices.md
> +- exitButton.setOnClickListener { viewModel.onExitButtonPressed() } - UI должен говорить вьюмодели - нажми на мою кнопку, а вьюмодель сама уже будет делать то, что надо
поправил

2022-06-10 01:37 UTC, anton6tak commented on university/memos/best-practices.md
> +- используйте аннотации `@Throws(...)` толко в случае, если это попадает в swift код
добавил

2022-06-10 01:39 UTC, anton6tak commented on university/memos/best-practices.md
> +- свои кастомные эксепшены, которые мы сами кидаем, наследуем от RuntimeException()
поправил

2022-06-10 01:42 UTC, anton6tak commented on university/memos/best-practices.md
> +- расставляйте элементы UI в xml в хронологическом порядке, а не абы как, чтобы те элементы, которые сверху экрана (тулбар например) объявлялись сверху в xml
поправил

2022-06-10 01:42 UTC, anton6tak commented on university/memos/best-practices.md
> +- форматирование кода, отключить галку, чтобы не добавлялась лишняя запятая ![img.png](media/useless-comma.png)
перенес

2022-06-10 01:43 UTC, anton6tak commented on university/memos/best-practices.md
> +- помните про конфикты имен Kotlin и iOS, если у вас будет свойство description, [вот](../../learning/kotlin-multiplatform/mobile-highlights#конфликты-имен-на-ios) что будет на iOS
переписал

2022-06-10 01:44 UTC, anton6tak commented on university/memos/best-practices.md
> +- цвет для контроллера надо устанавливать в AppDelegate, только создали навконтроллер - сразу ставим цвет `navigationController?.navigationBar.barStyle = .black`
добавил оба варианта

2022-06-10 01:46 UTC, anton6tak commented on university/memos/best-practices.md
> +- используйте слабые ссылки на self
поправил

2022-06-10 01:49 UTC, anton6tak commented on university/memos/best-practices.md
> +  - savedInstanceState - переменная для хранения данных из бандла, которая передается в onCreate(). Если данные из бандла пустые или savedInstanceState == null, тогда нужно создать новый навграф, а е
поправил

2022-06-10 01:49 UTC, anton6tak commented on university/memos/best-practices.md
> +- подписываться на вьюмодель должна создаваться сразу, как только мы создали вью
поправил

2022-06-10 03:09 UTC, anton6tak commented on university/memos/best-practices.md
> +- уделяйте пристальное внимание тому, как вы обрабатываете стейты
добавил напоминалку про ссылку на обработку стейтов на iOS

2022-06-10 03:26 UTC, anton6tak commented on university/memos/best-practices.md
> +- Конструкция `with(binding...)` для XML элементов. Не стоит ей злоупотреблять. Используйте ее только если вам предстоит работа с элементами минимум 3 уровня вложенности и обращение к этим элементам
добавил

2022-06-10 04:00 UTC, Alex009 requested changes

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +3. Не должно быть никакого хардкода текста, который показывается пользователю
", надо использовать строки локализации"

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +    - соит исопльзовать `binding`
стоит

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +           somethingButton.setOnClickListener { TODO() }
`setOnClickListener(::onSomethingPressed)`
Не допускайте сильной вложенности кода

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +10. Не создавайте дополнительную переменную, если она никак не улучшает читаемость кода
продумать

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +    - exitButton.setOnClickListener { viewModel.clearUserData() } - UI не должен говорить вьюмодели - чисти данные пользователя
выделить код

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +15. кликабельные элементы UI не сами думать, какой метод вьюмодели им вызывать
не должны сами решать

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +    - exitButton.setOnClickListener { viewModel.onExitButtonPressed() } - UI должен говорить вьюмодели - нажата кнопка `exitButton`, т.е. публичное API вьюмодели должно быть таким, чтобы по нему явно
выделить код

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +17. Используйте `weakLambda(...)` - сохранят receiver слабой ссылкой ***ссылка на доку***
https://kmm.icerock.dev/learning/libraries/moko/moko-units#можно-ли-передавать-лямбду-в-unititem

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +24. Все привязки вьюх к вьюмодели помещайте в одну функцию `bindToViewModel`
тут уточнить что не прям весь код привязки в ней, а что она должна выполнять привязку (даже путем вызова других функций, которые сделают привязку)

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +28. Не надо выдавать никакие данные из юнита (например по клику)
указать как правильно

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +30. Никогда не обрабатывайте Error-ы. у Throwable два наследника - Exception и Error. Эксепшены надо обрабатывать, они исправимы. а Error'ы - неисправимы. их не надо обрабатывать, приложение должно у
https://rollbar.com/blog/java-exceptions-hierarchy-explained/

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +8. Все `ViewController`-ы должны называться с окончанием `ViewController`, а не `Screen`, потому что `Screen`- это экран девайса. `ViewController` не обязательно занимает весь экран, их на экране сра
UITabBarController, модалки

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +7. ***В первом блоке курса***во `Fragment`-ах корутины нужно запускать во `viewLifecycleScope`, а не `lifecycleScope`. То есть цепляться ко вьюхе, а не к фрагменту
не только в первом блоке так

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +12. Константы класса должны находиться в `companionObject`, а в свойствах должно быть все то, что уникально для каждого экземпляра класса
`companion object`

2022-06-10 04:00 UTC, Alex009 commented on university/memos/best-practices.md
> +   - во всех UI элементах, которые содержат поле `text`, устанавливайте текст используя `tools:text`, чтобы было легче ориентироваться в дизайне экрана ***Я думаю это можно жестким требованием постав
не в требования практики, но в первый блок с указанием что эта штука существуует и ее надо юзать всегда для превью

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +3. Не должно быть никакого хардкода текста, который показывается пользователю
поправил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +    - соит исопльзовать `binding`
поправил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +    - exitButton.setOnClickListener { viewModel.clearUserData() } - UI не должен говорить вьюмодели - чисти данные пользователя
выделил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +15. кликабельные элементы UI не сами думать, какой метод вьюмодели им вызывать
поправил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +    - exitButton.setOnClickListener { viewModel.onExitButtonPressed() } - UI должен говорить вьюмодели - нажата кнопка `exitButton`, т.е. публичное API вьюмодели должно быть таким, чтобы по нему явно
выделил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +17. Используйте `weakLambda(...)` - сохранят receiver слабой ссылкой ***ссылка на доку***
добавил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +24. Все привязки вьюх к вьюмодели помещайте в одну функцию `bindToViewModel`
дописал

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +30. Никогда не обрабатывайте Error-ы. у Throwable два наследника - Exception и Error. Эксепшены надо обрабатывать, они исправимы. а Error'ы - неисправимы. их не надо обрабатывать, приложение должно у
добавил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +8. Все `ViewController`-ы должны называться с окончанием `ViewController`, а не `Screen`, потому что `Screen`- это экран девайса. `ViewController` не обязательно занимает весь экран, их на экране сра
добавил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +7. ***В первом блоке курса***во `Fragment`-ах корутины нужно запускать во `viewLifecycleScope`, а не `lifecycleScope`. То есть цепляться ко вьюхе, а не к фрагменту
поправил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +12. Константы класса должны находиться в `companionObject`, а в свойствах должно быть все то, что уникально для каждого экземпляра класса
поправил

2022-06-10 06:02 UTC, anton6tak commented on university/memos/best-practices.md
> +   - во всех UI элементах, которые содержат поле `text`, устанавливайте текст используя `tools:text`, чтобы было легче ориентироваться в дизайне экрана ***Я думаю это можно жестким требованием постав
добавил

2022-06-10 06:04 UTC, anton6tak commented on university/memos/best-practices.md
> +28. Не надо выдавать никакие данные из юнита (например по клику)
поправил

2022-06-10 06:30 UTC, anton6tak commented on university/memos/best-practices.md
> +           somethingButton.setOnClickListener { TODO() }
добавил

2022-06-10 06:37 UTC, anton6tak commented on university/memos/best-practices.md
> +10. Не создавайте дополнительную переменную, если она никак не улучшает читаемость кода
чет не придумывается ничего все равно,  оставил пока так

2022-06-10 06:49 UTC, anton6tak commented on university/memos/best-practices.md
> +  ```
выкинул пока пример

2022-06-10 11:25 UTC, Alex009 approved these changes

2022-06-10 11:27 UTC, merged