moko-kswift page
Alex009/kmm.icerock.dev pull request #53
Opened 2022-06-11 14:30 UTC by anton6tak

2022-06-15 04:01 UTC, Alex009 requested changes

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +- `enum`-ы, соответствующие `sealed-interface`-ам из общего кода, чтобы работать их в `switch` без ветки `default`
чтобы использовать

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +- `extensions`, объявленные в общем коде
экстеншены к платформенным классам (типа UILabel) и интерфейсам.
обычные экстеншены к котлин классам и так норм работают, без kswift

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +Детали подключения плагина вы можете узнать из его [README](https://github.com/icerockdev/moko-kswift#readme) и [стати](https://medium.com/icerock/how-to-implement-swift-friendly-api-with-kotlin-mult
статьи

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +При подключении плагина `moko-kswift` он добавит следующие такски в gradle:
таски

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +- `mpp-library/Tasks/cocoapods/kSwiftMultiplatformLibraryPodspec` - если подключен наш плагин [dev.icerock.mobile.multiplatform.ios-framework](https://github.com/icerockdev/mobile-multiplatform-gradl
`:mpp-library:kSwiftMultiplatformLibraryPodspec`

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +- `mpp-library-pods/Tasks/cocoapods/kSwiftmpp_library_podsPodspec` - если подключен плагин [cocoapods](https://kotlinlang.org/docs/native-cocoapods.html) от JetBrains
`mpp-library-pods:kSwiftmpp_library_podsPodspec`

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +- `mpp-library/Tasks/cocoapods/kSwiftMultiplatformLibraryPodspec` - если подключен наш плагин [dev.icerock.mobile.multiplatform.ios-framework](https://github.com/icerockdev/mobile-multiplatform-gradl
`kSwift` + framework name + `Podspec` - имя таски. группа- `cocoapods`

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +Обе эти таски генерируют `mpp-library/MultiplatformLibrarySwift.podspec` файл.
framework_name + `Swift.podspec`

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +- Меньше конфликтов с именами, файл доступен только там, где мы его подключили
сгенерированные классы и методы доступны только там

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +- Лучше воспроизводимость - `buildPhase` на сборку Kotlin-кода всегда происходит при компиляции пода
(реже будет ситуация непонятной ошибки из-за не скомпилированного заранее котлин модуля)

2022-06-15 04:01 UTC, Alex009 commented on learning/libraries/moko/moko-kswift.md
> +Поэтому, единственным вариантом остается подключать сгенерированные файлы к проекту - добавить их вручную (находятся по пути `../shared/build/cocoapods/framework/sharedSwift/..`).
этот путь только при использовании подов будет доступен.
а при интегарции напрямую надо юзать таску которую я в примере скидывал

2022-06-15 11:09 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +- `enum`-ы, соответствующие `sealed-interface`-ам из общего кода, чтобы работать их в `switch` без ветки `default`
поправил

2022-06-15 11:09 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +- `extensions`, объявленные в общем коде
дописал

2022-06-15 11:09 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +Детали подключения плагина вы можете узнать из его [README](https://github.com/icerockdev/moko-kswift#readme) и [стати](https://medium.com/icerock/how-to-implement-swift-friendly-api-with-kotlin-mult
поправил

2022-06-15 11:09 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +При подключении плагина `moko-kswift` он добавит следующие такски в gradle:
поправил

2022-06-15 11:09 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +- `mpp-library/Tasks/cocoapods/kSwiftMultiplatformLibraryPodspec` - если подключен наш плагин [dev.icerock.mobile.multiplatform.ios-framework](https://github.com/icerockdev/mobile-multiplatform-gradl
добавил

2022-06-15 11:09 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +- `mpp-library-pods/Tasks/cocoapods/kSwiftmpp_library_podsPodspec` - если подключен плагин [cocoapods](https://kotlinlang.org/docs/native-cocoapods.html) от JetBrains
поправил

2022-06-15 11:10 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +Обе эти таски генерируют `mpp-library/MultiplatformLibrarySwift.podspec` файл.
поправил

2022-06-15 11:10 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +- Меньше конфликтов с именами, файл доступен только там, где мы его подключили
поправил

2022-06-15 11:10 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +- Лучше воспроизводимость - `buildPhase` на сборку Kotlin-кода всегда происходит при компиляции пода
добавил

2022-06-15 11:11 UTC, anton6tak commented on learning/libraries/moko/moko-kswift.md
> +Поэтому, единственным вариантом остается подключать сгенерированные файлы к проекту - добавить их вручную (находятся по пути `../shared/build/cocoapods/framework/sharedSwift/..`).
поправил

2022-06-16 03:49 UTC, Alex009 approved these changes

2022-06-16 03:54 UTC, merged