ios state
Alex009/kmm.icerock.dev pull request #55
Opened 2022-06-14 10:43 UTC by anton6tak

2022-06-15 04:09 UTC, Alex009 requested changes

2022-06-15 04:09 UTC, Alex009 commented on learning/ios/state.md
> +# Обработка State
слить с андроидной страницей про стейты, положить рядом с "многопоточность". назвать "Единый стейт экрана"

2022-06-15 04:09 UTC, Alex009 commented on learning/ios/state.md
> +Это позволяет нам создать `let` константы, проинициализировать их в `switch case` в зависимости от стейта и присвоить вьюхам их значения.
про константы поправить

2022-06-16 03:30 UTC, anton6tak commented on learning/ios/state.md
> +# Обработка State
Сделал одну страницу

2022-06-16 03:30 UTC, anton6tak commented on learning/ios/state.md
> +Это позволяет нам создать `let` константы, проинициализировать их в `switch case` в зависимости от стейта и присвоить вьюхам их значения.
поправил

2022-06-16 04:00 UTC, Alex009 approved these changes

2022-06-16 06:35 UTC, merged