sharing data between fragments and activities
Alex009/kmm.icerock.dev pull request #9
Opened 2022-03-10 10:03 UTC by anton6tak

2022-03-14 06:49 UTC, Alex009 requested changes

2022-03-14 06:49 UTC, Alex009 commented on learning/android/data-sharing.md
> +- завязка экранов на предыдущих -> проблемы при пересоздании экранов (отсутствие данных, полученных с прошлого экрана, которые лежали в кеше и стерлись, например, из-за ошибки памяти) //переписать
ну так переписать же надо :)

2022-03-14 06:49 UTC, Alex009 commented on learning/android/data-sharing.md
> +- без проблем можно было сохранить в `Bundle`, обезопасившись от привязки на данные от предыдущего экрана при неожиданной ошибке или пересозданию экрана
>какие-нибудь ключи

не понятно будет. что за ключи? я сам не понимаю щас что за ключи предлагается передавать) id-шники - понятно

2022-03-14 06:49 UTC, Alex009 commented on learning/android/data-sharing.md
> +В первую очередь стоит отметить, что передавать стоит только id-шники или ключи, по которым получатель обратится к репозиторию и получит нужные данные. Это обезопасит вас от таких проблем, как:
а во вторую очередь надо отметить что мы должны использовать функции `createIntent` у activity и `createArguments` у fragment чтобы создавать intent/bundle для перехода.
И описать что это уменьшает дублирование, прячет детали реализации экрана от внешних классов и дает строгое api для перехода на экран

2022-03-14 06:49 UTC, Alex009 commented on learning/android/data-sharing.md
> +В первую очередь стоит отметить, что передавать стоит только id-шники или ключи, по которым получатель обратится к репозиторию и получит нужные данные. Это обезопасит вас от таких проблем, как:
это частично в примере реализации описано, но только для фрагмента и без чтения аргумента в самом фрагменте.
надо показать и чтение аргументов самим экраном и передачу другими экранами и имена использовать для функций те что выше комментмо указаны

2022-03-15 03:49 UTC, anton6tak commented on learning/android/data-sharing.md
> +- завязка экранов на предыдущих -> проблемы при пересоздании экранов (отсутствие данных, полученных с прошлого экрана, которые лежали в кеше и стерлись, например, из-за ошибки памяти) //переписать
поправил

2022-03-15 05:04 UTC, anton6tak commented on learning/android/data-sharing.md
> +- без проблем можно было сохранить в `Bundle`, обезопасившись от привязки на данные от предыдущего экрана при неожиданной ошибке или пересозданию экрана
поправил

2022-03-15 05:04 UTC, anton6tak commented on learning/android/data-sharing.md
> +В первую очередь стоит отметить, что передавать стоит только id-шники или ключи, по которым получатель обратится к репозиторию и получит нужные данные. Это обезопасит вас от таких проблем, как:
Дописал

2022-03-22 09:36 UTC, Alex009 approved these changes

2022-03-22 09:36 UTC, merged